/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Alunos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Agencias = new javax.swing.JMenu();
        AgenciaIncluir = new javax.swing.JMenuItem();
        AgenciaAlterar = new javax.swing.JMenuItem();
        AgenciaExcluir = new javax.swing.JMenuItem();
        AgenciaConsultar = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        ClientesIncluir = new javax.swing.JMenuItem();
        ClientesAlterar = new javax.swing.JMenuItem();
        ClientesExcluir = new javax.swing.JMenuItem();
        ClientesConsultar = new javax.swing.JMenuItem();
        ContaCorrente = new javax.swing.JMenu();
        ContaCorrenteIncluir = new javax.swing.JMenuItem();
        ContaCorrenteAlterar = new javax.swing.JMenuItem();
        ContaCorrenteExcluir = new javax.swing.JMenuItem();
        ContaCorrenteConsultar = new javax.swing.JMenuItem();
        Histórico = new javax.swing.JMenu();
        HistóricoIncluir = new javax.swing.JMenuItem();
        HistóricoAlterar = new javax.swing.JMenuItem();
        HistóricoExcluir = new javax.swing.JMenuItem();
        HistóricoConsultar = new javax.swing.JMenuItem();
        Movimentação = new javax.swing.JMenu();
        MovimentaçãoIncluir = new javax.swing.JMenuItem();
        MovimentaçãoAlterar = new javax.swing.JMenuItem();
        MovimentaçãoExcluir = new javax.swing.JMenuItem();
        MovimentaçãoConsultar = new javax.swing.JMenuItem();
        Usuários = new javax.swing.JMenu();
        UsuáriosIncluir = new javax.swing.JMenuItem();
        UsuáriosAlterar = new javax.swing.JMenuItem();
        UsuáriosExcluir = new javax.swing.JMenuItem();
        UsuáriosConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Agencias.setText("Agências");

        AgenciaIncluir.setText("Incluir");
        AgenciaIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaIncluirActionPerformed(evt);
            }
        });
        Agencias.add(AgenciaIncluir);

        AgenciaAlterar.setText("Alterar");
        AgenciaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaAlterarActionPerformed(evt);
            }
        });
        Agencias.add(AgenciaAlterar);

        AgenciaExcluir.setText("Excluir");
        AgenciaExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaExcluirActionPerformed(evt);
            }
        });
        Agencias.add(AgenciaExcluir);

        AgenciaConsultar.setText("Consultar");
        AgenciaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaConsultarActionPerformed(evt);
            }
        });
        Agencias.add(AgenciaConsultar);

        jMenuBar1.add(Agencias);

        Clientes.setText("Clientes");

        ClientesIncluir.setText("Incluir");
        ClientesIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesIncluirActionPerformed(evt);
            }
        });
        Clientes.add(ClientesIncluir);

        ClientesAlterar.setText("Alterar");
        ClientesAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesAlterarActionPerformed(evt);
            }
        });
        Clientes.add(ClientesAlterar);

        ClientesExcluir.setText("Excluir");
        ClientesExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesExcluirActionPerformed(evt);
            }
        });
        Clientes.add(ClientesExcluir);

        ClientesConsultar.setText("Consultar");
        ClientesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesConsultarActionPerformed(evt);
            }
        });
        Clientes.add(ClientesConsultar);

        jMenuBar1.add(Clientes);

        ContaCorrente.setText("Conta Corrente");

        ContaCorrenteIncluir.setText("Incluir");
        ContaCorrenteIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaCorrenteIncluirActionPerformed(evt);
            }
        });
        ContaCorrente.add(ContaCorrenteIncluir);

        ContaCorrenteAlterar.setText("Alterar");
        ContaCorrenteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaCorrenteAlterarActionPerformed(evt);
            }
        });
        ContaCorrente.add(ContaCorrenteAlterar);

        ContaCorrenteExcluir.setText("Excluir");
        ContaCorrenteExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaCorrenteExcluirActionPerformed(evt);
            }
        });
        ContaCorrente.add(ContaCorrenteExcluir);

        ContaCorrenteConsultar.setText("Consultar");
        ContaCorrenteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaCorrenteConsultarActionPerformed(evt);
            }
        });
        ContaCorrente.add(ContaCorrenteConsultar);

        jMenuBar1.add(ContaCorrente);

        Histórico.setText("Histórico");

        HistóricoIncluir.setText("Incluir");
        HistóricoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistóricoIncluirActionPerformed(evt);
            }
        });
        Histórico.add(HistóricoIncluir);

        HistóricoAlterar.setText("Alterar");
        HistóricoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistóricoAlterarActionPerformed(evt);
            }
        });
        Histórico.add(HistóricoAlterar);

        HistóricoExcluir.setText("Excluir");
        HistóricoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistóricoExcluirActionPerformed(evt);
            }
        });
        Histórico.add(HistóricoExcluir);

        HistóricoConsultar.setText("Consultar");
        HistóricoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistóricoConsultarActionPerformed(evt);
            }
        });
        Histórico.add(HistóricoConsultar);

        jMenuBar1.add(Histórico);

        Movimentação.setText("Movimentação");

        MovimentaçãoIncluir.setText("Incluir");
        MovimentaçãoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentaçãoIncluirActionPerformed(evt);
            }
        });
        Movimentação.add(MovimentaçãoIncluir);

        MovimentaçãoAlterar.setText("Alterar");
        MovimentaçãoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentaçãoAlterarActionPerformed(evt);
            }
        });
        Movimentação.add(MovimentaçãoAlterar);

        MovimentaçãoExcluir.setText("Excluir");
        MovimentaçãoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentaçãoExcluirActionPerformed(evt);
            }
        });
        Movimentação.add(MovimentaçãoExcluir);

        MovimentaçãoConsultar.setText("Consultar");
        MovimentaçãoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentaçãoConsultarActionPerformed(evt);
            }
        });
        Movimentação.add(MovimentaçãoConsultar);

        jMenuBar1.add(Movimentação);

        Usuários.setText("Usuários");

        UsuáriosIncluir.setText("Incluir");
        UsuáriosIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuáriosIncluirActionPerformed(evt);
            }
        });
        Usuários.add(UsuáriosIncluir);

        UsuáriosAlterar.setText("Alterar");
        UsuáriosAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuáriosAlterarActionPerformed(evt);
            }
        });
        Usuários.add(UsuáriosAlterar);

        UsuáriosExcluir.setText("Excluir");
        UsuáriosExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuáriosExcluirActionPerformed(evt);
            }
        });
        Usuários.add(UsuáriosExcluir);

        UsuáriosConsultar.setText("Consultar");
        UsuáriosConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuáriosConsultarActionPerformed(evt);
            }
        });
        Usuários.add(UsuáriosConsultar);

        jMenuBar1.add(Usuários);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgenciaExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaExcluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        JFAgencias agencias = new JFAgencias(operacao);
        agencias.setVisible(true);
    }//GEN-LAST:event_AgenciaExcluirActionPerformed

    private void AgenciaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaAlterarActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        JFAgencias agencias = new JFAgencias(operacao);
        agencias.setVisible(true);
    }//GEN-LAST:event_AgenciaAlterarActionPerformed

    private void AgenciaIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaIncluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        JFAgencias agencias = new JFAgencias(operacao);
        agencias.setVisible(true);
    }//GEN-LAST:event_AgenciaIncluirActionPerformed

    private void ClientesIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesIncluirActionPerformed
        String operacao = "Incluir";
        JFCliente cliente = new JFCliente(operacao);
        cliente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesIncluirActionPerformed

    private void ClientesAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesAlterarActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        JFCliente cliente = new JFCliente(operacao);
        cliente.setVisible(true);
    }//GEN-LAST:event_ClientesAlterarActionPerformed

    private void ClientesExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesExcluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        JFCliente cliente = new JFCliente(operacao);
        cliente.setVisible(true);
    }//GEN-LAST:event_ClientesExcluirActionPerformed

    private void ContaCorrenteIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaCorrenteIncluirActionPerformed
        String operacao = "Incluir";
        JFContaCorrente contacorrente = new JFContaCorrente(operacao);
        contacorrente.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ContaCorrenteIncluirActionPerformed

    private void ContaCorrenteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaCorrenteAlterarActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        JFContaCorrente contacorrente = new JFContaCorrente(operacao);
        contacorrente.setVisible(true);
    }//GEN-LAST:event_ContaCorrenteAlterarActionPerformed

    private void ContaCorrenteExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaCorrenteExcluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        JFContaCorrente contacorrente = new JFContaCorrente(operacao);
        contacorrente.setVisible(true);
    }//GEN-LAST:event_ContaCorrenteExcluirActionPerformed

    private void HistóricoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistóricoIncluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        JFHistorico historico = new JFHistorico(operacao);
        historico.setVisible(true);       
    }//GEN-LAST:event_HistóricoIncluirActionPerformed

    private void HistóricoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistóricoAlterarActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        JFHistorico historico = new JFHistorico(operacao);
        historico.setVisible(true); 
    }//GEN-LAST:event_HistóricoAlterarActionPerformed

    private void HistóricoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistóricoExcluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        JFHistorico historico = new JFHistorico(operacao);
        historico.setVisible(true); 
    }//GEN-LAST:event_HistóricoExcluirActionPerformed

    private void MovimentaçãoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentaçãoIncluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        JFMovimentacao movimentacao = new JFMovimentacao(operacao);
        movimentacao.setVisible(true);  
    }//GEN-LAST:event_MovimentaçãoIncluirActionPerformed

    private void MovimentaçãoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentaçãoAlterarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String operacao = "Alterar";
        JFMovimentacao movimentacao = new JFMovimentacao(operacao);
        movimentacao.setVisible(true);  
    }//GEN-LAST:event_MovimentaçãoAlterarActionPerformed

    private void MovimentaçãoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentaçãoExcluirActionPerformed
        // TODO add your handling code here:
         String operacao = "Excluir";
        JFMovimentacao movimentacao = new JFMovimentacao(operacao);
        movimentacao.setVisible(true);  
    }//GEN-LAST:event_MovimentaçãoExcluirActionPerformed

    private void UsuáriosIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuáriosIncluirActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        JFUsuario usuario = new JFUsuario(operacao);
        usuario.setVisible(true); 
    }//GEN-LAST:event_UsuáriosIncluirActionPerformed

    private void UsuáriosAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuáriosAlterarActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        JFUsuario usuario = new JFUsuario(operacao);
        usuario.setVisible(true); 
    }//GEN-LAST:event_UsuáriosAlterarActionPerformed

    private void UsuáriosExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuáriosExcluirActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String operacao = "Excluir";
        JFUsuario usuario = new JFUsuario(operacao);
        usuario.setVisible(true); 
    }//GEN-LAST:event_UsuáriosExcluirActionPerformed

    private void AgenciaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaConsultarActionPerformed
        // TODO add your handling code here:
         String operacao = "Consultar";
        JFAgencias agencias = new JFAgencias(operacao);
        agencias.setVisible(true);
    }//GEN-LAST:event_AgenciaConsultarActionPerformed

    private void UsuáriosConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuáriosConsultarActionPerformed

        // TODO add your handling code here:
        String operacao = "Consultar";
        JFUsuario usuario = new JFUsuario(operacao);
        usuario.setVisible(true); 
    }//GEN-LAST:event_UsuáriosConsultarActionPerformed

    private void ClientesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesConsultarActionPerformed
        // TODO add your handling code here:
        String operacao = "Consultar";
        JFCliente cliente = new JFCliente(operacao);
        cliente.setVisible(true);
    }//GEN-LAST:event_ClientesConsultarActionPerformed

    private void ContaCorrenteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaCorrenteConsultarActionPerformed
        // TODO add your handling code here:
        String operacao = "Consultar";
        JFContaCorrente contacorrente = new JFContaCorrente(operacao);
        contacorrente.setVisible(true);
    }//GEN-LAST:event_ContaCorrenteConsultarActionPerformed

    private void HistóricoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistóricoConsultarActionPerformed
        // TODO add your handling code here:
        String operacao = "Consultar";
        JFHistorico historico = new JFHistorico(operacao);
        historico.setVisible(true); 
    }//GEN-LAST:event_HistóricoConsultarActionPerformed

    private void MovimentaçãoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentaçãoConsultarActionPerformed
        // TODO add your handling code here:
        String operacao = "Consultar";
        JFMovimentacao movimentacao = new JFMovimentacao(operacao);
        movimentacao.setVisible(true);  
    }//GEN-LAST:event_MovimentaçãoConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgenciaAlterar;
    private javax.swing.JMenuItem AgenciaConsultar;
    private javax.swing.JMenuItem AgenciaExcluir;
    private javax.swing.JMenuItem AgenciaIncluir;
    private javax.swing.JMenu Agencias;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem ClientesAlterar;
    private javax.swing.JMenuItem ClientesConsultar;
    private javax.swing.JMenuItem ClientesExcluir;
    private javax.swing.JMenuItem ClientesIncluir;
    private javax.swing.JMenu ContaCorrente;
    private javax.swing.JMenuItem ContaCorrenteAlterar;
    private javax.swing.JMenuItem ContaCorrenteConsultar;
    private javax.swing.JMenuItem ContaCorrenteExcluir;
    private javax.swing.JMenuItem ContaCorrenteIncluir;
    private javax.swing.JMenu Histórico;
    private javax.swing.JMenuItem HistóricoAlterar;
    private javax.swing.JMenuItem HistóricoConsultar;
    private javax.swing.JMenuItem HistóricoExcluir;
    private javax.swing.JMenuItem HistóricoIncluir;
    private javax.swing.JMenu Movimentação;
    private javax.swing.JMenuItem MovimentaçãoAlterar;
    private javax.swing.JMenuItem MovimentaçãoConsultar;
    private javax.swing.JMenuItem MovimentaçãoExcluir;
    private javax.swing.JMenuItem MovimentaçãoIncluir;
    private javax.swing.JMenu Usuários;
    private javax.swing.JMenuItem UsuáriosAlterar;
    private javax.swing.JMenuItem UsuáriosConsultar;
    private javax.swing.JMenuItem UsuáriosExcluir;
    private javax.swing.JMenuItem UsuáriosIncluir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
